Generate parent-ids / Fix up canDrop logic
teamious/FormBuilder pull request #115
Opened 2017-05-24 23:48 UTC by asinner

2017-05-24 23:57 UTC, linweigao requested changes

2017-05-24 23:57 UTC, linweigao commented on src/components/FormBuilder.tsx
> +<<<<<<< HEAD
Did you need merge this?

2017-05-24 23:57 UTC, linweigao commented on docs/src/components/DemoPage.tsx
> +        if (target.field && source.field.id === target.field.id) {
This logic should belong to formBuilder, no?

2017-05-24 23:57 UTC, linweigao commented on docs/src/components/DemoPage.tsx
> +        if (source.field.id && source.parentId !== target.parentId) {
This logic should belong to nestedFormBuilder or FormBuilder.

2017-05-24 23:57 UTC, linweigao commented on docs/src/components/DemoPage.tsx
> +        if (source.index !== undefined && source.index === target.index - 1) {
Sam here

2017-05-25 00:07 UTC, asinner commented on src/components/FormBuilder.tsx
> +<<<<<<< HEAD
fixed

2017-05-25 00:07 UTC, asinner commented on docs/src/components/DemoPage.tsx
> +        if (source.field.id && source.parentId !== target.parentId) {
done

2017-05-25 00:07 UTC, asinner commented on docs/src/components/DemoPage.tsx
> +        if (target.field && source.field.id === target.field.id) {
done

2017-05-25 00:07 UTC, asinner commented on docs/src/components/DemoPage.tsx
> +        if (source.index !== undefined && source.index === target.index - 1) {
done

2017-05-25 00:22 UTC, linweigao commented on src/components/NestedForm/NestedFormBuilder.tsx
> +        if (source.field.type === 'NestedForm' &&  target.parentId) {
source.field.type === this.prop.field.type. Is this better instead of hard coding?

2017-05-25 00:30 UTC, linweigao approved these changes

2017-05-25 00:30 UTC, asinner commented on src/components/NestedForm/NestedFormBuilder.tsx
> +        if (source.field.type === 'NestedForm' &&  target.parentId) {
done

2017-05-25 00:31 UTC, merged