add radio component
teamious/FormBuilder pull request #138
Opened 2017-08-18 09:27 UTC by 1297947244

2017-08-21 03:05 UTC, linweigao requested changes

2017-08-21 03:05 UTC, linweigao commented on docs/src/components/fields/RadioGroupField.ts
> +    label: '单选按钮',
??

2017-08-21 03:05 UTC, linweigao commented on docs/src/components/fields/RadioGroupField.ts
> +    displayName: '单选按钮',
??

2017-08-21 03:05 UTC, linweigao commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +export default class RadioGroupOptionEditor extends React.PureComponent<IFieldOptionEditorProps, IState> {
React.PureComponent<IFieldOptionEditorProps, void>

if not state.

2017-08-21 03:05 UTC, linweigao commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +                    {fields.map((item) => {
Maybe we have a common control already, check how the dropdown field is implemented.

2017-08-21 03:05 UTC, linweigao commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +            type: "ABCDEFG"
what's this type used for?

2017-08-21 03:05 UTC, linweigao commented on docs/src/components/fields/RadioGroupField.ts
> +            type: 'ABCDEFG',
What's this type used for?

2017-08-21 05:51 UTC, closed without merging

2017-08-22 01:48 UTC, pleasureswx123 commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +                            >X</a>
X是否可以用html特殊字符替代？

2017-08-22 01:50 UTC, pleasureswx123 commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +        field.fields.map((item, index) => {
fields属性是否一定存在？

2017-08-22 01:52 UTC, pleasureswx123 commented on docs/src/components/fields/RadioGroupField.ts
> +            label: 'IOS',
value是否可以提出？作为常量？