radio component
teamious/FormBuilder pull request #139
Opened 2017-08-21 07:23 UTC by 1297947244

2017-08-22 02:40 UTC, linweigao requested changes

2017-08-22 02:40 UTC, linweigao commented on docs/src/components/fields/RadioGroupField.ts
> +    fields: [
这个不应该放在fields里，fields是给嵌套用的。

这个应该放在options里

2017-08-22 02:40 UTC, linweigao commented on docs/src/components/fields/RadioGroupField.ts
> +            type: 'ABCDEFG',
What's this type used for?

2017-08-22 02:40 UTC, linweigao commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +export default class RadioGroupOptionEditor extends React.PureComponent<IFieldOptionEditorProps, IState> {
If there is no state, you can use 'void'.

=> React.PureComponent<IFieldOptionEditorProps, void>

2017-08-22 02:40 UTC, linweigao commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +                    {fields.map((item) => {
Why not use <OrderedListInput /> component?

2017-08-22 02:40 UTC, linweigao commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +            type: "ABCDEFG"
Why did you hardcode?

2017-08-22 02:40 UTC, linweigao commented on docs/src/components/fields/RadioGroupTextField.tsx
> +                                    value={others.value}
This cannot work. field.option is form template definition. It cannot be saved into each data, and it won't change unless someone use option editor to modify.

The value in the props is the only information which will be saved in the database. Value can be a jObject if necessary.

2017-08-22 09:02 UTC, 1297947244 commented on docs/src/components/fields/RadioGroupField.ts
> +    fields: [
Done.

2017-08-22 09:02 UTC, 1297947244 commented on docs/src/components/fields/RadioGroupField.ts
> +            type: 'ABCDEFG',
type是为了表示每组radio的名字， 修改为name。

2017-08-22 09:02 UTC, 1297947244 commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +export default class RadioGroupOptionEditor extends React.PureComponent<IFieldOptionEditorProps, IState> {
Done.

2017-08-22 09:02 UTC, 1297947244 commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +                    {fields.map((item) => {
删除盒子组件将单独做一个组件提交，不在radio中实现。

2017-08-22 09:02 UTC, 1297947244 commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +            type: "ABCDEFG"
Done.

2017-08-22 09:08 UTC, linweigao commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +            id: labelArr[labelArr.length - 1].id + this.addOptionId++,
what's the logic for the id generator?
1,2,4,7,11?

2017-08-23 03:44 UTC, 1297947244 commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +            id: labelArr[labelArr.length - 1].id + this.addOptionId++,
原想法是  新增加的选项id，根据最后一个选项的id拼接0，1，2，3...
现已删除 create，remove 逻辑，使用OrderedListInput component。

2017-08-23 03:44 UTC, 1297947244 commented on docs/src/components/fields/RadioGroupOptionEditor.tsx
> +                    {fields.map((item) => {
已使用OrderedListInput component

2017-08-23 03:48 UTC, 1297947244 commented on docs/src/components/fields/SingleSelectorField.ts
> +        selectOpts: ['a', 'b', 'c'],
Repair the demo drop-down box error.

2017-08-28 21:39 UTC, linweigao approved these changes

2017-08-28 21:39 UTC, linweigao commented on docs/src/components/App.scss
> + .dotted-box {
Where do you need this css?

2017-08-29 09:36 UTC, 1297947244 commented on docs/src/components/App.scss
> + .dotted-box {
Sorry, I forgot to delete it.

2017-08-29 21:06 UTC, merged